### ISSUE TITLE
时序数据库预研

### ISSUE THREAD

**Issue by bass-player** [DvcLAB/DvcLAB#11]
## DB
1. [influxdb](https://www.influxdata.com/get-influxdb/)
2. [prometheus](https://prometheus.io/)

## Step
1. [conoha](https://www.conoha.jp/vps/)，[vultr](https://www.vultr.com/)云服务器平台上注册VPS
1.1 至少2核4G内存
1.2 Ubuntu Server 20.04
1.3 本地xshell访问         (3.1)
2. 使用docker (docker-compoose) 安装influxdb / prometheus
2.1 了解docker/docker-compose     (3.2)
3. 学习API文档，构建Java测试用例/curl/postman，连接数据进行基本读写查询操作      (3.3)
4. TSDB Scheme整理，寻找常用的使用范例，构建Java测试用例，形成使用文档    （3.5）
5. 数据可视化工具的安装试用        
5.1 使用docker (docker-compoose) 安装
5.2 https://redash.io/
5.3 https://grafana.com/
5.4 https://www.metabase.com/          （3.8）

**Comment by Scisaga** [comment]
参考：
1. [时间序列数据库 (TSDB)](https://www.jianshu.com/p/31afb8492eff)

**Comment by Scisaga** [comment]
[InfluxDB 部署及常用配置](https://docs.google.com/document/d/1pOv-7XcWSioqy6vZiAeA2uT-NadYUudvQKemvFybKXs/)
