### ISSUE TITLE
dvclab.com待解决bug

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcLAB#13]
- [x] PsiAI产品展示图片中，有部分用户信息需要遮盖
- [x] 网页底部备案号需链接至"http://beian.miit.gov.cn/"

**Comment by Scisaga** [comment]
**动态效果无法显示**
现象：
1. 首次加载无法触发动态效果，console提示错误信息，刷新页面后可正常触发
原因分析：
1. 需要分析console提示的错误信息，有可能触发执行时间点问题，在资源加载完成前触发了动态效果，参考：https://developer.mozilla.org/zh-TW/docs/Web/API/Window/load_event
