### ISSUE TITLE
基于Google Docs/Slides的Wiki系统设计

### ISSUE THREAD

**Issue by 117503445** [DvcLAB/DvcLAB#16]
# 目标

- [ ] 1. 把Google Drive 中的文档有效组织起来
  - [ ] a. 使用[wiki.js](https://github.com/Requarks/wiki) 创建 Google Drive 文档的索引页
  - [ ] b. 提供 Google 无缝登录服务
- [ ] 2. 作为工具套件之一，更方便的集成
  - [ ] a. [KeyCloak](https://github.com/keycloak/keycloak)登录
  - [ ] b. Docker Compose部署

**Comment by Scisaga** [comment]
参考：
1. [PUBLISH GOOD LOOKING GOOGLE DOCS](https://gdoc.pub/)
2. [Publish files as web pages](https://support.google.com/a/users/answer/9308870?hl=en)
