### ISSUE TITLE
部署集群监控

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcLAB#18]
1. 参考《使用node_exporter监控服务器状态》在各服务器（10, 11, 20, 21, 22, 23, 30, 31, 32）使用docker部署node_exporter
  1.1. 卸载其他方式部署的node_exporter
2. 确认Prometheus正常运行
3. 升级Grafana版本至7，并导入监控模板，测试数据收集和监控展示功能

**Comment by JJLAAA** [comment]
1、2完成，3待完成

**Comment by JJLAAA** [comment]
完成
