### ISSUE TITLE
OpenResty动态路由配置验证及tunnel配置操作

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcLAB#24]
1. 验证可以将 `/users/${user_id}/containers/${container_id}` 映射到  `${host}:port`
2. dvclab-tunnel-2 配置域名 j.dvclab.com
3. dvclab-tunnel-2 部署Java11、OpenResty、MySQL、frps，并测试

**Comment by JJLAAA** [comment]
已完成，并更新文档
