### ISSUE TITLE
Keycloak中client设置汇总

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcLAB#25]
1. [x] 设置用户Realm角色和默认用户角色
        参考给[用户添加默认的Role](https://docs.google.com/document/d/152Lpdf3ndyisMpTok6KML9FSP1mNebjg4vKWohyc7X0/edit#heading=h.vho9taxtk3uu)
2. [x] 获取用户详情API
       https://${addr}/auth/realms/${realm}/protocol/openid-connect/userinfo
       parameters:  access_token:${access_token}
3. [x] 梳理endpoints及使用场景
    [Keycloak的Endpoints及使用场景](https://docs.google.com/document/d/1T6DYNI38FmLPihUe9pIW1xj06X8THipzWZ0iKcbwF7w/edit#heading=h.o2u0e3hpvyj)
3. [x] 更新到《Keycloak简明指南》

**Comment by linstein** [comment]
将用户设置为某个Realm的管理员，用户登录后可以直接跳转到Realm的UI管理页面
