### ISSUE TITLE
Keycloak结合服务场景的配置研究

### ISSUE THREAD

**Issue by linstein** [DvcLAB/DvcLAB#29]
1. 用户前端登录后，如何判断当前用户是否被禁用？
2. 用户创建容器后，如何更新Keycloak中的用户权限？
3. 如何判断用户对于某资源或网页是否有访问权限？
4. Keycloak如何与Git，s3，nextcloud等服务进行使用？
5. 从其它的已登录页面访问jupyterlab页面时可以直接进入页面

**Comment by Scisaga** [comment]
introspect endpoint 返回数据应包含以下字段
1. username
2. email
3. avatar_url
4. enabled

**Comment by linstein** [comment]
在User的配置页面，可以将用户设置为disable，被disabled的用户将无法登录
![image](https://user-images.githubusercontent.com/38755884/111024129-e241a800-8417-11eb-8ee0-907a696a72ce.png)

**Comment by linstein** [comment]
如何判断用户对于某资源或网页是否有访问权限？

1. 开启User Manage Access，让用户有权管理资源，能将资源分享给其它用户
2. 将该用户作为Owner在Client中创建对应Resource
```
POST https://auth.dvclab.com/auth/realms/DvcLAB/authz/protection/resource_set
header: Authorization : Bearer ${PAT}
Body: 
{
    "name":"test_create_2",
     "type":"test",
     "owner": "linstein",
     "ownerManagedAccess": true,
     "resource_scopes":[
         "visit",
         "viewing"
      ]
}
```

3. 采用基于用户的访问策略,此时只有资源的资源的Owner和被分享用户才有权访问资源。
4. 用户可在账号管理页面管理资源的访问权限。
![image](https://user-images.githubusercontent.com/38755884/111253216-c9223c80-864d-11eb-80d9-1399a52b00a1.png)

**Comment by linstein** [comment]
给已有账号绑定第三方登录：
1. 登录用户个人账户管理网页
`https://auth.dvclab.com/auth/realms/DvcLAB/account/`
2. 选择关联身份，添加即可
![image](https://user-images.githubusercontent.com/38755884/111259595-30de8480-865a-11eb-9106-33f1afc8fc1a.png)
3. 进行验证

**Comment by linstein** [comment]
验证基于UMA的资源授权流程
参考：
1. [Understanding UMA and Keycloak](https://www.janua.fr/understanding-uma-and-keycloak/)
2. [User-Managed Access (UMA) 2.0 Grant for OAuth 2.0 Authorization](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html)

**Comment by linstein** [comment]
UMA授权流程：
1. Client请求Resource Server访问资源，不带有token。
2. Resource Server发现Client请求不带有token，它会向Authorization Server 索要一个Permission Ticket（阐明Scope ）
3. Resouce Server将获得的permission ticket放置在header中，返回给Client；同时也会返回Authorization URL
4. Client访问Authorization Server，带上permission ticket和client credential参数，为了获取RPT token
5. Resource Server会查看permission ticket以及它具有的Scope，然后会查询与这个Scope有关的Policy，接着会验证这些Policy，如果结果为True，就会返回RPT Token给Client。
6. Client将带着得到的RPT token访问Resource Server的资源API，Resource Server通过introspect token endpoint验证该token，验证成功返回资源。
![image](https://user-images.githubusercontent.com/38755884/112721249-dc7eb300-8f3d-11eb-8dc0-fdf5b8ad3041.png)

**Comment by linstein** [comment]
Keycloak中的资源授权流程：
1. 在Keycloak的Authorization面板中创建Resource、Policy、Scope，并通过Permission进绑定
2. Client带着access_token请求Resource Server
3. Resource Server根据请求的URL参数查找Keycloak对应的Resource Id和Scope，并带着收到的access token请求permission endpoint获取permission ticket
4. Resource Server将permission ticket返回给Client，Client带着Permission ticket和access_token请求Keycloak获取RPT
5. 获取成功后将RPT返回给Resource Server，Resource Server带着RPT和base64编码的 $client_id:$client_secret在introspect endpoint进行验证，解析出资源的name和scope信息，并据此返回资源给Client

**Comment by linstein** [comment]
Keycloak通过API给资源创建Policy是，指定特定用户可以访问；但如果此用户是资源的Owner时，虽然创建绑定成功，但并未生效。需要寻找原因

**Comment by linstein** [comment]
使用admin api无法给资源创建、绑定Permission，需要使用Resource Owner的access token
```
{
    "error": "invalid_request",
    "error_description": "Only resource owner can access policies for resource [d85afe47-6066-42d5-a581-77dbd297a172]"
}
```

**Comment by linstein** [comment]
1. 开启User Manage Access后，如果用户定义的policy和系统内设置的policy冲突，则以用户的自定义policy为主，如下图：
![image](https://user-images.githubusercontent.com/38755884/113416511-18a98c00-93f4-11eb-89ee-6a42e4a117e0.png)

2. 这里系统定义的Policy是指，通过UI管理页面定义的Policy和Permission。
![Uploading image.png…]()
