### ISSUE TITLE
修改dvclab.com图片

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcLAB#32]
- [x] 修改[DvcLAB官网](https://www.dvclab.com/)中第三页的PsiPiper架构图，并部署

**Comment by Liuqianyik** [comment]
已修改图片，并提交至仓库，未部署

**Comment by goodmornight** [comment]
- [ ] 1. 图片颜色改一下
- [ ] 2. 中文改为英文
- [ ] 3. 布局稍微改一下
@Liuqianyik

**Comment by Liuqianyik** [comment]
收到，预计13号完成并提交

**Comment by Liuqianyik** [comment]
已提交修改后的图片到分支

**Comment by goodmornight** [comment]
已看到修改内容，麻烦把*的文字换回原来的英文。 @Liuqianyik

**Comment by Liuqianyik** [comment]
收到，已修改
