### ISSUE TITLE
Openresty解析JupyterLab地址问题

### ISSUE THREAD

**Issue by linstein** [DvcLAB/DvcLAB#34]
解析过程如下：
1. 本地启动JupyterLab镜像，通过frp将端口映射到跳板机的一个端口上
2. 跳板上使用openresty将此端口解析成/usr/xxxxx/container/xxxx的形式

存在问题：

- [x] 1. JupyterLab的默认路径是 /lab，因此当直接访问 http://{跳板机ip}/usr/xxx/container/xxx时会自动跳转到/lab下，且提示500错误

- [x] 2. 在访问通过openresty解析的网址时，修改保存ipynb文件提示413错误，表示请求实体过大。推测是需要对openresty进行相应的参数配置  @JJLAAA

**Comment by linstein** [comment]
对于第一个问题目前采用如下解决方式：
1. 修改JupyterLab的配置文件，将默认的base_url由  "/" 修改为  "/usr/xxxx/container/xxxxxx"
2. base_url通过环境变量传进去
3. 同时openresty方面在转发时也要带上 "/usr/xxxx/container/xxxxxx"以及相关的参数，如code=xxxx

但上面的那种方法相当于在容器中写死了用户访问地址，目前还有另一种想法：
JupyterLab的base_url保持不变是 "/" ,而openresty转发时在所有的路径前面加上 "/usr/xxxx/container/xxxxxx"

**Comment by JJLAAA** [comment]
- [ ] 可尝试使用`proxy_redirect`解决
