### ISSUE TITLE
IFTTT与Web Scraper的调研

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcLAB#37]
## 内容

1. 学习使用[IFTTT](https://ifttt.com/)并整理成PPT。
2. 学习使用[Web Scraper](https://chrome.google.com/webstore/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=zh-CN)并整理成PPT。

**Comment by Liuqianyik** [comment]
收到，预计周天完成并提交ppt
